config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  # devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :orders
  resources :ordered_books
  resources :categories
  resources :books

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'landing#index'
  get :about, to: 'static_pages#about'

  get :cart, to: 'cart#show'
  patch :add_item_to_cart, to: 'cart#add_item'
  delete :clear_cart, to:'cart#clear_cart'
  delete :remove_book, to:'cart#remove_book'
  patch :update_book, to: "cart#update_book"

  get :order_confirmation, to: 'addresses#order_confirmation'



end

app/models/ordered_book.rb
class OrderedBook < ApplicationRecord

  belongs_to :order
  belongs_to :book

end

app/controllers/ordered_books_controller.rb
class OrderedBooksController < ApplicationController
  before_action :set_ordered_book, only: [:show, :edit, :update, :destroy]

  # GET /ordered_books
  # GET /ordered_books.json
  def index
    @ordered_books = OrderedBook.all
  end

  # GET /ordered_books/1
  # GET /ordered_books/1.json
  def show
  end

  # GET /ordered_books/new
  def new
    @ordered_book = OrderedBook.new
  end

  # GET /ordered_books/1/edit
  def edit
  end

  # POST /ordered_books
  # POST /ordered_books.json
  def create
    @ordered_book = OrderedBook.new(ordered_book_params)

    respond_to do |format|
      if @ordered_book.save
        format.html { redirect_to @ordered_book, notice: 'Ordered book was successfully created.' }
        format.json { render :show, status: :created, location: @ordered_book }
      else
        format.html { render :new }
        format.json { render json: @ordered_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordered_books/1
  # PATCH/PUT /ordered_books/1.json
  def update
    respond_to do |format|
      if @ordered_book.update(ordered_book_params)
        format.html { redirect_to @ordered_book, notice: 'Ordered book was successfully updated.' }
        format.json { render :show, status: :ok, location: @ordered_book }
      else
        format.html { render :edit }
        format.json { render json: @ordered_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordered_books/1
  # DELETE /ordered_books/1.json
  def destroy
    @ordered_book.destroy
    respond_to do |format|
      format.html { redirect_to ordered_books_url, notice: 'Ordered book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordered_book
      @ordered_book = OrderedBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordered_book_params
      params.require(:ordered_book).permit(:book_id, :order_id, :quantity)
    end
end

app/helpers/ordered_books_helper.rb
module OrderedBooksHelper
end

app/views/ordered_books/_form.html.erb
<%= form_for(ordered_book) do |f| %>
  <% if ordered_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ordered_book.errors.count, "error") %> prohibited this ordered_book from being saved:</h2>

      <ul>
      <% ordered_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %>
    <%= f.number_field :book_id %>
  </div>

  <div class="field">
    <%= f.label :order_id %>
    <%= f.number_field :order_id %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ordered_books/edit.html.erb
<h1>Editing Ordered Book</h1>

<%= render 'form', ordered_book: @ordered_book %>

<%= link_to 'Show', @ordered_book %> |
<%= link_to 'Back', ordered_books_path %>

app/views/ordered_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordered Books</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Order</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordered_books.each do |ordered_book| %>
      <tr>
        <td><%= ordered_book.book_id %></td>
        <td><%= ordered_book.order_id %></td>
        <td><%= ordered_book.quantity %></td>
        <td><%= link_to 'Show', ordered_book %></td>
        <td><%= link_to 'Edit', edit_ordered_book_path(ordered_book) %></td>
        <td><%= link_to 'Destroy', ordered_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ordered Book', new_ordered_book_path %>

app/views/ordered_books/new.html.erb
<h1>New Ordered Book</h1>

<%= render 'form', ordered_book: @ordered_book %>

<%= link_to 'Back', ordered_books_path %>

app/views/ordered_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @ordered_book.book_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @ordered_book.order_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @ordered_book.quantity %>
</p>

<%= link_to 'Edit', edit_ordered_book_path(@ordered_book) %> |
<%= link_to 'Back', ordered_books_path %>