config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  # devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :orders
  resources :ordered_books
  resources :categories
  resources :books

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'landing#index'
  get :about, to: 'static_pages#about'

  get :cart, to: 'cart#show'
  patch :add_item_to_cart, to: 'cart#add_item'
  delete :clear_cart, to:'cart#clear_cart'
  delete :remove_book, to:'cart#remove_book'
  patch :update_book, to: "cart#update_book"

  get :order_confirmation, to: 'addresses#order_confirmation'



end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :read_cart, only: [:show, :add_item, :update_book, :remove_book]
  after_action :write_cart, only: [:add_item, :clear_cart, :update_book, :remove_book]

  def show
    @books = []
    @totalprice = 0
    @cart.each do |book_id,quantity|

      book = Book.find_by(id: book_id)
      book.define_singleton_method(:quantity) do
        quantity
      end

      @books << book

      @totalprice += book.price.to_f * book.quantity.to_i
    end
  end

  def add_item
    if @cart[params[:book_id]]
      quantity = params[:quantity].to_i
      oldquantity = @cart[params[:book_id]].to_i
      @cart[params[:book_id]] = quantity + oldquantity

      # @cart[params[:book_id]] = @cart[params[:book_id]].to_i + params[:quantity].to_i
      # flash[:success] = "Book has been added to shopping cart."

    else
      @cart[params[:book_id]] = params[:quantity]
    end
  end

  def clear_cart
    @cart = {}
    redirect_to cart_path
  end

  def write_cart
    cookies[:cart] = JSON.generate @cart
  end

  def read_cart
    if cookies[:cart]
      @cart = JSON.parse cookies[:cart]
    else
      @cart = {}
    end
  end

  def update_book
    if @cart[params[:book_id]]
      @cart[params[:book_id]] = params[:quantity]
    end
    redirect_to cart_path
  end

  def remove_book
    @cart.delete params[:book_id]
    flash[:success] = "Book deleted from shopping cart."
    redirect_to cart_path
  end
end

app/views/cart/show.html.erb
<div class="container">
  <div class="col-md-12">

    <% @books.each do |book| %>
    <div class="row thumbnail">
      <div class="col-sm-3 col-lg-3 col-md-3">
        <%= image_tag book.image, class: "list-img" %> <br/>
      </div>

      <div class="caption">
        <span class="col-sm-3 col-lg-3 col-md-3">
          <%= label_tag "Book details:", nil, class: "text-left" %> </br>
          <%= link_to book.title, book %> <br/>
          <%= book.author %> <br/>
        </span>

        <span class="col-sm-2 col-lg-2 col-md-2">
          <%= form_tag update_book_path(book_id: book.id), method: :patch do %>
          <span class="small-1 large-1 columns pull-left">
            <%= label_tag "Quantity:", nil, class: "right inline" %>
          </span>
          <span class="small-1 large-1 columns pull-left">
            <%= text_field_tag :quantity, book.quantity %>
          </span>
          <span class="small-1 large-1 columns pull-left">
            <%= submit_tag 'Update', class: "button" %>
          </span>
        <%end%>
        </span>

        <span class="col-sm-2 col-lg-2 col-md-2">
          <%= label_tag "Price:", nil, class: "text-left" %> </br>
          <%= number_to_currency(book.price, unit: "RM ") %>
        </span>
      </div>

      <span class="col-sm-2 col-lg-2 col-md-2">
        <%= link_to "Remove Book", remove_book_path(book_id: book.id), method: :delete %>
      </span>
    </div>
    <% end %>

    <div class ="row">
    <div class="col-sm-12 col-lg-12 col-md-12 text-right">
      <%= label_tag "Total Order Price: ", nil, class: "text-left" %>
      <%= number_to_currency(@totalprice, unit: "RM ") %>

    </div>
  </div>

  </div>
</div>




<div class="container">
  <div class="row text-center">
    <%= link_to "Clear cart ", clear_cart_path, method: :delete %>|
    <%= link_to "Pay Now", root_path %></br>
  </div>
</div>