config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  # devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :orders
  resources :ordered_books
  resources :categories
  resources :books

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'landing#index'
  get :about, to: 'static_pages#about'

  get :cart, to: 'cart#show'
  patch :add_item_to_cart, to: 'cart#add_item'
  delete :clear_cart, to:'cart#clear_cart'
  delete :remove_book, to:'cart#remove_book'
  patch :update_book, to: "cart#update_book"

  get :order_confirmation, to: 'addresses#order_confirmation'



end

app/models/book.rb
class Book < ApplicationRecord

  has_many :ordered_books
  has_many :orders, through: :ordered_books
  belongs_to :category

  searchkick

  mount_uploader :image, ImageUploader

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    if params[:query].present?
        Book.reindex
        @query = params[:query]
        @books = Book.search(params[:query], page: params[:page])
      else
        @books = Book.all.page params[:page]
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :category_id, :description, :price, :image)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <div id="preview-image">
       <% if @book.image? %>
         <%= image_tag @book.image, class: "img-settings img-responsive center-block" %>
       <% end %>
     </div>

    <%= f.label :image %>
    <%= f.file_field :image, id: "book_image_field", class: 'form-control image-uploader' %>
  </div>


  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= collection_select(:book, :category_id, Category.all, :id, :genre) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

        <p>
          <h1 style = text-align:center>All Books </h1>
        </p>
        <% @books.each do |book| %>
          <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
              <div class="caption">
                    <%= image_tag book.image %> <br/>
                    <%= link_to book.title, book_path(book) %> <br/>
                    <%= book.author %> <br/>
                    <%= book.category.genre %> <br/>
                    <%= book.description %> <br/>
                    <%= number_to_currency(book.price, unit: "RM ") %> <br/>
                    <%= link_to 'Book Details', book_path(book), class:"btn btn-info btn-sm" %>
                    <%= link_to 'Add To Cart', add_item_to_cart_path(book_id: book, quantity: 1), method: :patch, class:"btn btn-info btn-sm" %>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

<!--
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Author</th>
      <th>Category</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= image_tag book.image %></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.category_id %></td>
        <td><%= book.description %></td>
        <td><%= number_to_currency(book.price, unit: "RM ") %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div> -->

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="container">
    <div class="col-md-12">

      <div class="row thumbnail">
        <span class="col-sm-3 col-lg-3 col-md-3">
          <%= image_tag @book.image %>
        </span>

        <div class="caption">
          <span class="col-sm-9 col-lg-9 col-md-9">
            <h4>  <%= number_to_currency(@book.price, unit: "RM ") %></h4>
            <h4><%= @book.title %></h4>
            <p><%= @book.author %></p>
            <p><%= @book.category.genre %></p>
            <p><%= @book.description %></p>
          </span>
        </div>
          <%= link_to 'Back', books_path, class:"btn btn-info btn-sm" %>
          <%= link_to 'Add To Cart', add_item_to_cart_path(book_id: @book, quantity: 1), method: :patch, class:"btn btn-info btn-sm" %>
      </div>
    </div>
  </div>
</div>