config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  # devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :orders
  resources :ordered_books
  resources :categories
  resources :books

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'landing#index'
  get :about, to: 'static_pages#about'

  get :cart, to: 'cart#show'
  patch :add_item_to_cart, to: 'cart#add_item'
  delete :clear_cart, to:'cart#clear_cart'
  delete :remove_book, to:'cart#remove_book'
  patch :update_book, to: "cart#update_book"

  get :order_confirmation, to: 'addresses#order_confirmation'



end

app/models/category.rb
class Category < ApplicationRecord

  has_many :books
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:genre)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.genre %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <div class="row">

    <div class="col-md-3">
      <p class="lead">Categories</p>
      <div class="list-group">
        <% @categories.each do |category| %>
        <%= link_to category.genre, category_path(category), class: 'list-group-item' %><br />
        <% end %>
      </div>
    </div>


    <div class="col-md-9">
      <div class="row">
        <p>
          <h3 style = text-align:center><%= @category.genre %></h3>
        </p>
        <% @category.books.each do |book| %>
        <div class="col-sm-4 col-lg-4 col-md-4">
          <div class="thumbnail">
            <div class="caption">
              <%= image_tag book.image %><br/>
              <%= link_to book.title, book_path(book) %> <br/>
              <%= book.author %> <br/>
              <%= book.description %> <br/>
              <%= number_to_currency(book.price, unit: "RM ") %> <br/>
              <%= link_to 'Back', category_path, class:"btn btn-info btn-sm" %>
              <%= link_to 'Add To Cart', add_item_to_cart_path(book_id: book, quantity: 1), method: :patch, class:"btn btn-info btn-sm" %>
            </div>
          </div>
        </div>
        <% end %>
      </div>


    </div>
  </div>
</div>